name: ton_client_dart
description: Provide binding to TON SDK Library. TON SDK Library provides all heavy-computation components and functions, such as TON Virtual Machine, TON Transaction Executor, ABI-related functions, boc-related functions, crypto functions.
version: 0.1.2
homepage: https://github.com/freetonsurfer/ton_client_dart/

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  ffi: ^2.0.2
  tuple: ^2.0.2
  convert: ^3.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  
